### ISSUE TITLE
Hactoberfest

### ISSUE THREAD

**Issue by TUSHAR75194** [Raghavarya2002/DSA#242]

**Comment by Jay3Chauhan** [comment]
can i solve this issue?

**Comment by abhint1** [comment]
please give detail and assign it to me

**Comment by Jay3Chauhan** [comment]
backtracking algorithm in java

**Comment by Jay3Chauhan** [comment]
This all are mine
Jay3chauhan

**Comment by Raghavarya2002** [comment]
> can i solve this issue?

which issue?
