### ISSUE TITLE
M-Coloring Problem

### ISSUE THREAD

**Issue by sumitbaroniya** [Raghavarya2002/DSA#276]
Please assign me this issue under hacktoberfest.

**Comment by Raghavarya2002** [comment]
> Please assign me this issue under hacktoberfest.

okay

**Comment by Raghavarya2002** [comment]
> Please assign me this issue under hacktoberfest.

this repo is excluded from hacktoberfest due to some reasons, even I don't know the exact reason. you can contribute in my other repos according to you skills like web dev, android dev or python.
Thanks
