### ISSUE TITLE
Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by abhishekiiitr** [Raghavarya2002/DSA#315]
Hello @Raghavarya2002 ,
Please Assign this issue to me under Hactoberfest!

**Comment by Raghavarya2002** [comment]
> Hello @Raghavarya2002 , Please Assign this issue to me under Hactoberfest!

this repo is excluded from hacktoberfest due to some reasons, even I don't know the exact reason. you can contribute in my other repos according to you skills like web dev, android dev or python.
Thanks
