### ISSUE TITLE
cycle sort algorithem

### ISSUE THREAD

**Issue by shubham1091** [Raghavarya2002/DSA#320]
added some leetcode cycle sort Q. solution in hacktoberfest2022 folder please merge my request

**Comment by Raghavarya2002** [comment]
> added some leetcode cycle sort Q. solution in hacktoberfest2022 folder please merge my request

this repo is excluded from hacktoberfest due to some reasons, even I don't know the exact reason. you can contribute in my other repos according to you skills like web dev, android dev or python.
Thanks
